
dubbo:
  application:
    name: springboot-dubbo-customer
  protocol:
    name: dubbo
    port: 20881
    ## 这里配置配置中心的地址
  config-center:
    protocol: zookeeper
    address: zookeeper://127.0.0.1:2181
