server:
  port: 8091

dubbo:
  application:
    name: springboot-dubbo-provider
  protocol:
    name: dubbo
    port: 20882
    ## 这里配置配置中心的地址
  config-center:
    protocol: zookeeper
    address: zookeeper://127.0.0.1:2181




